### ISSUE TITLE
Nested key/values not imported correctly from locale yml file

### ISSUE THREAD

**Issue by brianweiner** [infinum/phrasing#19]
Hello,

I've been playing with Phrasing for a few days now, it's pretty slick - so thanks for making it available.

I noticed that the creation of PhrasingPhrases during i18n interception behaves differently than importing a file. For example:

I have Phrasing installed and running, I also use devise. If i login/logout, the Devise localization messages are automatically detected by Phrasing and imported. I get key / value pairs like this:

devise.confirmations.confirmed   Hi, %{first_name}! Welcome to MyWebsite!

So far so good.

What if I want to import my locale file to begin with, this way my end-user can begin modifying his locale messages immediately and is not required for them to have appeared first.

If I import a basic yaml document

```
france:
  hello: "Hello world"
  devise:
    confirmations:
      confirmed: "Hi, %{first_name}! Welcome to MyWebsite!"
      confirmed_seller: "Hi, %{first_name}! Your %{trial_length} day trial has started. You should %{ad_path}"
      send_instructions: "You will receive an email with instructions about how to confirm your account in a few minutes."
      send_paranoid_instructions: "If your email address exists in our database, you will receive an email with instructions about how to confirm your account in a few minutes."
```

The import behavior, however, only seems to recognize the "devise" key, and the other nested keys are just lumped into one big hashy value. This sometimes generates an error "TypeError: can't cast Hash to text", but sometimes it 'works' - but doesn't generate a useful key/value pair.

["key", "devise"], ["locale", "france"], ["updated_at", Thu, 13 Feb 2014 18:47:18 UTC +00:00], ["value", {"confirmations"=>{"confirmed"=>"Hi, %{first_name}! Welcome to MyWebsite!", "confirmed_seller"=>"Hi, %{first_name}! Your %{trial_length} day trial has started. You should %{ad_path}", "send_instructions"=>"You will receive an email with instructions about how to confirm your account in a few minutes.", "send_paranoid_instructions"=>"If your email address exists in our database, you will receive an email with instructions about how to confirm your account in a few minutes."}}]]

I wrote a bit of a modified PhrasingPhrase model to create dot separated nested key values from the larger hash. It works for me, but I doubt it's the ideal way to do it. 

a private method:

```
def self.flatten_hash(my_hash, parent=[])
  my_hash.flat_map do |key, value|
    case value
      when Hash then flatten_hash( value, parent+[key] )
      else [(parent+[key]).join('.'), value]
    end
  end
end
```

and then in the import_yaml method:

```
hash.each do |locale, data|
    flat_array = self.flatten_hash(data) 
    nested_hash = Hash[*flat_array]
    nested_hash.each do |key, value|
```

the rest is the same.

Any thoughts? Am I not formatting my locale yml document correctly? Is this not a use case you all have bumped into?

Thanks!
